databases:
  - name: Chillow
    databaseName: chillow_postgres
    user: hyunbink

services:
  - type: web
    name: Chillow
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres://chillow_postgres_user:R2oGNWKonHChOiAnRF4n7Wqoo7B5lSuZ@dpg-cjs14rlm702s738pvl4g-a.oregon-postgres.render.com/chillow_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: LANG
        value: en_US.UTF-8
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: SECRET_KEY_BASE
        sync: false
